version: "3"

services:
    cypress:
        container_name: Cypress
        restart: always
        image: "cypress/included:7.0.0"
        entrypoint: cypress install
        entrypoint: cypress open --project /e2e
        working_dir: /e2e
        volumes:
            - /c/data/:/e2e 
        ports: ["3000:3000"]
        
        entrypoint: npm start
        

        